### ISSUE TITLE
Kotlin version incompatiblity

### ISSUE THREAD

**Issue by alpeshvasani** [jonasbark/flutter_in_app_update#101]
The module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

<img width="1381" alt="image" src="https://github.com/jonasbark/flutter_in_app_update/assets/26425141/e1114b44-2e3a-414d-9789-5aeea0364470">

**Comment by jonasbark** [comment]
Hi! 
Please use in_app_update: ^4.1.4 which uses the lowest possible kotlin version. This version is also the default for new flutter projects.

https://github.com/jonasbark/flutter_in_app_update/blob/master/example/android/build.gradle#L2
