### ISSUE TITLE
Install Update State Listener

### ISSUE THREAD

**Issue by ViniciusSossela** [jonasbark/flutter_in_app_update#102]
It should have an Install Update State Listener, to track if the update was installed or not.

**Comment by ViniciusSossela** [comment]
> you could repeat the check to see if it's installed or not - or do you mean something entirely different?

Yeah, we could do that, but actually, I have created a PR to do this install tracking, I think it's a better approach than checking again for new updates.

**Comment by ViniciusSossela** [comment]
> > you could repeat the check to see if it's installed or not - or do you mean something entirely different?
> 
> Yeah, we could do that, but actually, I have created a PR to do this install tracking, I think it's a better approach than checking again for new updates. https://developer.android.com/guide/playcore/in-app-updates/kotlin-java#monitor-flexible-state
> 
> #103

Would you be able to review it @jonasbark  ? Otherwise, we will be using the forked pub reference version. (https://github.com/ViniciusSossela/flutter_in_app_update)

**Comment by jonasbark** [comment]
Released as of 4.2.0
