### ISSUE TITLE
[Proposal] convert the plugin to use `plugin_platform_interface`

### ISSUE THREAD

**Issue by navaronbracke** [jonasbark/flutter_in_app_update#106]
The plugin ecosystem has evolved into providing platform specific implementations behind a common platform interface.

This enables adding support for multiple platforms in a modular way. (for example if we ever decide to support web or desktop)

We should consider to rewrite the plugin to follow this practice.

As the plugin is intended for Android only at this time (and the API surface is very limited), this should be a relatively simple task (regenerate the plugin from the new template, and move over the Android implementation details)

We might have to look into updating the public API to allow for specific arguments depending on the platform.
I'd propose to do that after the initial migration is done. (since this will be a breaking change)

I can look into this if desired, as I have prior experience with this kind of migration.

**Comment by jonasbark** [comment]
I thought about this as well, but I really don't see any benefit to it. Android is the only platform supported and I don't see how any other platform could ever be supported in a similar way.
