### ISSUE TITLE
Update dialog not showing in version 4.2.1

### ISSUE THREAD

**Issue by razer-santhosh** [jonasbark/flutter_in_app_update#112]
E/MethodChannel#de.ffuf.in_app_update/methods(30433): Failed to handle method call
E/MethodChannel#de.ffuf.in_app_update/methods(30433): java.lang.IllegalArgumentException: kotlin.Unit
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at de.ffuf.in_app_update.InAppUpdatePlugin.checkAppState(InAppUpdatePlugin.kt:206)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at de.ffuf.in_app_update.InAppUpdatePlugin.performImmediateUpdate(InAppUpdatePlugin.kt:193)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at de.ffuf.in_app_update.InAppUpdatePlugin.onMethodCall(InAppUpdatePlugin.kt:86)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at android.os.Looper.loopOnce(Looper.java:240)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at android.os.Looper.loop(Looper.java:351)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at android.app.ActivityThread.main(ActivityThread.java:8427)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MethodChannel#de.ffuf.in_app_update/methods(30433): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/DartMessenger(30433): Uncaught exception in binary message listener
E/DartMessenger(30433): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(30433): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/DartMessenger(30433): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
E/DartMessenger(30433): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)

$ flutter doctor -v
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2283], locale en-IN)
    • Flutter version 3.13.6 on channel stable at E:\Flutter_SDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (8 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\SSG\AppData\Local\Android\sdk
    • Platform android-UpsideDownCake, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\SSG\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\SSG\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • RMX3563 (mobile)  • T8SSAEL7U8GE5TRS • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 117.0.5938.134
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

**Comment by jonasbark** [comment]
Please show some code so I could possibly reproduce it.

**Comment by razer-santhosh** [comment]
previously, I tried it in emulator...But, in real device it's working good

**Comment by razer-santhosh** [comment]
previously, I tried it in emulator...But, in real device it's working good
