### ISSUE TITLE
Update dialog not showing in version 4.2.2

### ISSUE THREAD

**Issue by RomilPipaliya** [jonasbark/flutter_in_app_update#113]
Update dialog not showing in version 4.2.2

I'm showing update dialog after calling this  functions >  InAppUpdate.completeFlexibleUpdate()

**Comment by jonasbark** [comment]
What is that supposed to mean? When did it last work? 
Did you fully read and follow the readme?

**Comment by jonasbark** [comment]
And what does "not work" mean exactly?

**Comment by RomilPipaliya** [comment]
> And what does "not work" mean exactly?
```dart
InAppUpdate.completeFlexibleUpdate()
```
your completeFlexibleUpdate() function is not working cause of Android minimum SDK version is 16 and Playstore compulsory required is 21

**Comment by jonasbark** [comment]
I don't have a clue what this has to do with anything. Please provide proper information and sources.

**Comment by RomilPipaliya** [comment]
> I don't have a clue what this has to do with anything. Please provide proper information and sources.

Check this path 

https://github.com/jonasbark/flutter_in_app_update/blob/master/android/build.gradle where 

defaultConfig {
        minSdkVersion 16
    }
    
Change minSdkVersion from 16 to 21 and Run your example code

**Comment by RomilPipaliya** [comment]
> Yes, it's true that in app updates are only available from 21 upwards. I will adjust the readme accordingly but I still do not understand your point.
> 
> You are complaining that the plugin doesn't work on old Android versions?

It's not just about old Android versions, not working on any version

**Comment by jonasbark** [comment]
Did you try to change it and uploaded a new version? It really makes zero sense.

**Comment by RomilPipaliya** [comment]
> Did you try to change it and uploaded a new version? It really makes zero sense.

I just download your source code and make changes as i need and use it 
I'm just want to inform about the issue now decision is yours you want to fix it leave it whatever it is.

**Comment by ProZhar** [comment]
The same problem but with a fatal crash [link](https://github.com/jonasbark/flutter_in_app_update/issues/115)

**Comment by RomilPipaliya** [comment]
> The same problem but with a fatal crash [link](https://github.com/jonasbark/flutter_in_app_update/issues/115)

   just download source code and make changes as you need and use it

**Comment by jonasbark** [comment]
It works fine like this with all of our production apps, so I'm closing this.
