### ISSUE TITLE
Update download but not installed

### ISSUE THREAD

**Issue by androdevsatyam** [jonasbark/flutter_in_app_update#117]
Logs that i got 
AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore(18872): UID: [10809]  PID: [18872] AppUpdateService : linkToDeath
I/PlayCore(18872): UID: [10809]  PID: [18872] OnRequestInstallCallback : onRequestInfo
I/PlayCore(18872): UID: [10809]  PID: [18872] AppUpdateService : Unbind from service.
I/PlayCore(18872): UID: [10809]  PID: [18872] AppUpdateService : completeUpdate(com.instamate.com)
I/PlayCore(18872): UID: [10809]  PID: [18872] AppUpdateService : Initiate binding to the service.
I/PlayCore(18872): UID: [10809]  PID: [18872] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore(18872): UID: [10809]  PID: [18872] AppUpdateService : linkToDeath

**Comment by jonasbark** [comment]
https://github.com/jonasbark/flutter_in_app_update/issues/53
