### ISSUE TITLE
PlatformException(TASK_FAILURE, -9: Install Error(-9): The Play Store app is either not installed or not the official version.

### ISSUE THREAD

**Issue by VitaliBov** [jonasbark/flutter_in_app_update#118]
The unofficial Play Store bug has been detected on some devices:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(TASK_FAILURE, -9: Install Error(-9): The Play Store app is either not installed or not the official version. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_PLAY_STORE_NOT_FOUND), null, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at InAppUpdate.checkForUpdate(in_app_update.dart:62)
```

Devices (data from Crashlytics):

- Galaxy A12 - Android 11
- Tecno Spark Go 2022 - Android 11
- Galaxy S24 - Android 14
- Model:MOA-LX9N - Android 10
- Honor X9b 5G - Android 13
- Galaxy S10 5G - Android 12
- Galaxy A03s - Android 13
- Galaxy J2 Core - Android 8.1.0
- Galaxy S22 Ultra - Android 14
- V25 - Android 14
- Galaxy A41 - Android 12
- etc

**Comment by jonasbark** [comment]
I think the error message is pretty descriptive
