### ISSUE TITLE
PlatformException(TASK_FAILURE, -10: Install Error(-10) error

### ISSUE THREAD

**Issue by SaiGedelaMob** [jonasbark/flutter_in_app_update#121]
PlatformException(TASK_FAILURE, -10: Install Error(-10): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_APP_NOT_OWNED), null, null)

How can i fix it in flutter please help me.....

**Comment by orestesgaolin** [comment]
You first need to install the app as normal (e.g. from Internal or Closed test track) via Google Play using the same account as you use to download the APK via Play Internal App Sharing (e.g. if you have your developer account as name@gmail.com, then you need to first install the app using name@gmail.com account via Google Play, this makes the app as "owned by the user")

See this article for reference https://developer.android.com/guide/playcore/in-app-updates/test
