### ISSUE TITLE
Local test - ERROR_INSTALL_NOT_ALLOWED - Correct setup for release?

### ISSUE THREAD

**Issue by jksevend** [jonasbark/flutter_in_app_update#122]
Hi,
I followed the general instructions of your example in the documentation, you stated that local development is not possible, but how can i be sure that if i release it works? 

I want to perform an immediate update onPress (All other methods taken from example):

```
Card(
                  child: ListTile(
                    leading: const Icon(Icons.update),
                    title: Text(tr('settings.update.title')),
                    subtitle: Text(tr('settings.update.description')),
                    onTap: () async {
                      final updateInfo = await _checkForUpdate();
                      if (updateInfo.updateAvailability == UpdateAvailability.updateAvailable) {
                        await InAppUpdate.performImmediateUpdate().catchError((error) {
                          _showUpdateResultSnack(tr('settings.update.error'));
                          return AppUpdateResult.inAppUpdateFailed;
                        });
                      } else {
                        _showUpdateResultSnack(tr('settings.update.no_update'));
                      }
                    },
                  ),
                ),
```

And get this error when clicking locally:
`E/flutter ( 5178): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(TASK_FAILURE, -6: Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED), null, null)`

Is this expected behaviour? Am I correctly setup for release?
Also I am testing on emulator locally, is that the reason for the error?

Best,
Julian

**Comment by jksevend** [comment]
Spoiler:

It worked. Beautiful package.

**Comment by DurgeshSawantWYLD** [comment]
@jksevend  what was the issue, how did you make it work?
