### ISSUE TITLE
Update screen interferes with top bar

### ISSUE THREAD

**Issue by PhilippKolmann** [jonasbark/flutter_in_app_update#128]
Thanks for this wonderful package. We use it happily and today I saw on my Pixel 7, that it interferes with the OS top banner:

![image](https://github.com/user-attachments/assets/e280143b-c346-4572-8a70-5d34e01baf8e)

Could you please add https://api.flutter.dev/flutter/widgets/SafeArea-class.html or something similar, so that it doesn't interfere anymore with OS stuff?

**Comment by jonasbark** [comment]
There's no possibility to adjust anything in the UI, so there's nothing I can do here. It does not happen on my device either, so you may want to look at your styles.xml files in your android directory.
