### ISSUE TITLE
warning condition

### ISSUE THREAD

**Issue by imeDevelopers** [jonasbark/flutter_in_app_update#37]
[  +66 ms]
flutter path \ .pub-cache\hosted\pub.dartlang.org\in_app_update-1.1.11\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt:202:24: warning: condition 'state.installErrorCode() != null' is always 'true'
[  +49 ms]             } else if (state.installErrorCode() != null) {
[   +5 ms]                        ^

**Comment by jonasbark** [comment]
This was fixed a while ago
