### ISSUE TITLE
it does't work with bundle just with apk

### ISSUE THREAD

**Issue by mostafaahmederaqy** [jonasbark/flutter_in_app_update#41]

**Comment by pro100svitlo** [comment]
hey ho!
Is there any updates here?

**Comment by adarshhegde** [comment]
any updates? really don't want to bork my app if it doesn't support bundle

**Comment by jonasbark** [comment]
Does the official documentation to Android In App Update state that only APKs are supported?

**Comment by pro100svitlo** [comment]
> Does the official documentation to Android In App Update state that only APKs are supported?

no, otherwise this feature doesn't make any sense. google slowly but confidently migrating to  the appBundle.

**Comment by jonasbark** [comment]
As the package is using the official api app bundles should not be an issue. If I'm there are issues please provide more information, such as log output.

**Comment by iamsandeepsk** [comment]
Yes, I have also face this issue!

**Comment by pro100svitlo** [comment]
method failed `InAppUpdate.checkForUpdate()` with exception
```dart
MissingPluginException(No implementation found for method checkForUpdate on channel in_app_update)
```

**Comment by jonasbark** [comment]
@pro100svitlo are you using latest 1.1.13?

**Comment by pro100svitlo** [comment]
@jonasbark 
so, right now I was able to get update data. But its wrong:
```
InAppUpdateState{updateAvailable: false, immediateUpdateAllowed: false, flexibleUpdateAllowed: false, availableVersionCode: null}
```

To test it I create a release version with a much lower app version (and version name as well).

**Comment by jonasbark** [comment]
Does it show up as an update in play store itself?

**Comment by pro100svitlo** [comment]
Hm, that's very strange, but no.
when I open playstore - there is no `update button`.
probably for some reasons system think that everything is fine...
any ideas why?

**Comment by thakurkartik1901** [comment]
I have uploaded a test app(Bundle). When I increase app version it is not showing update available in test app. But in playstore it shows update button.

**Comment by wa11breaker** [comment]
> Hm, that's very strange, but no.
> when I open playstore - there is no `update button`.
> probably for some reasons system think that everything is fine...
> any ideas why?

Google Play will not update the application if it is installed from somewhere other than the Play Store.

**Comment by jonasbark** [comment]
Closing this issue as it's out of scope of this plugin
