### ISSUE TITLE
PlatformException(Failed to bind to the service., null, null, null)

### ISSUE THREAD

**Issue by hyungtaecf** [jonasbark/flutter_in_app_update#54]
I'm getting this error just when using it with one of my emulators (Nexus 6 API 27). I have another emulator (Pixel 3a API 29) and a real device where it works fine.

`I/flutter (16163): PlatformException(Failed to bind to the service., null, null, null)
I/flutter (16163):
I/flutter (16163): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
I/flutter (16163): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
I/flutter (16163): <asynchronous suspension>
I/flutter (16163): #2      InAppUpdate.checkForUpdate
package:in_app_update/in_app_update.dart:13
I/flutter (16163): <asynchronous suspension>
`

This error comes on the "checkForUpdate" method.

flutter doctor:

[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [versÃ£o 10.0.19041.630], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

• No issues found!

**Comment by larssn** [comment]
In dev mode or release mode?

**Comment by mrniamster** [comment]
Any fix to this? getting this on my emulator too ,  AOSP on IA Emulator (emulator-5554)

**Comment by jonasbark** [comment]
Should be caused by missing google services - please reopen a ticket if it appears again
