### ISSUE TITLE
How add custom UI for the updates?

### ISSUE THREAD

**Issue by yashwp** [jonasbark/flutter_in_app_update#74]
Hi,

I'm looking to create a custom UI kinda thing after `await InAppUpdate.checkForUpdate()` function, where I can show some custom UI instead of the default Google Play one.

How can we do that using this package? If it does not have the functionality, how can I do that?

Attaching a screenshot from one of the apps.
<img width="168" alt="image" src="https://user-images.githubusercontent.com/13454790/149146317-82cbba14-8ca5-4a83-a859-e019088394aa.png">

**Comment by jonasbark** [comment]
Why don't you use checkForUpdate to see if there's an update and then show your own UI?

**Comment by jonasbark** [comment]
Closing this due to lack of information
