### ISSUE TITLE
PlatformException(TASK_FAILURE, AppUpdateService : Binder has died., null, null)

### ISSUE THREAD

**Issue by mehul425** [jonasbark/flutter_in_app_update#77]
Got this Crash in Production app.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(TASK_FAILURE, AppUpdateService : Binder has died., null, null).
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:607)
       at MethodChannel._invokeMethod(platform_channel.dart:177)
       at InAppUpdate.checkForUpdate(in_app_update.dart:46)
       at HomeController.onInit(home_controller.dart:31)

**Comment by mehul425** [comment]
any update on this ??

**Comment by rootd** [comment]
I'm also experiencing this error.

**Comment by rootd** [comment]
Something seems to be broken at Google's site. https://issuetracker.google.com/issues/222530459

**Comment by mehul425** [comment]
Getting too many Crashes so pls help 
![Screenshot 2022-06-18 at 11 13 48 AM](https://user-images.githubusercontent.com/52601503/174424670-fb5dacfc-34f1-4ce2-bfc2-d9a698ceca20.png)

**Comment by rootd** [comment]
As I wrote, this seems to be an issue at Googe's site. There's nothing the package maintainer can do about it.

**Comment by Lazizbek97** [comment]
Does it work now? I'm facing same issue still

**Comment by jonasbark** [comment]
After implementing the fix suggested in https://github.com/jonasbark/flutter_in_app_update/issues/82#issuecomment-1296717382 I no longer see the issue in my app

**Comment by tejaswinidev24** [comment]
Any Solution?
I am also facing the same issue

**Comment by razer-santhosh** [comment]
I also faced same issue, then I used native_updater package,
NativeUpdater.displayUpdateAlert(
      context,
      forceUpdate: true,
 );

just use this code in android, it'll take care everything

**Comment by fleoparra** [comment]
In my case, I use:

```
  in_app_update:
    git:
      url: https://github.com/fleoparra/flutter_in_app_update.git
      ref: master
```
And I do not have this issue. Can someone, with the problem, test this?

**Comment by jonasbark** [comment]
Appppppaarently it was fixed with the latest Play Core update:
https://issuetracker.google.com/issues/222530459#comment16
