### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by akhilgorantala** [jonasbark/flutter_in_app_update#79]
`  AppUpdateInfo _updateInfo;

  Future<void> checkForUpdate() async {
    InAppUpdate.checkForUpdate().then((info) {
      setState(() {
        _updateInfo = info;
      });
    }).catchError((e) {
      //do nothing
    });
  }

  void updateApp() {
    _updateInfo?.updateAvailability == UpdateAvailability.updateAvailable
        ? () {
            InAppUpdate.performImmediateUpdate();
          }
        : null;
  }`
`  @override
  void initState() {
    checkForUpdate();
    updateApp();
  }`

**Comment by lappi** [comment]
Any updates?

**Comment by vantutrieu97** [comment]
any solution?

**Comment by akhilgorantala** [comment]
use Native Updater Package, 
https://pub.dev/packages/native_updater

**Comment by jonasbark** [comment]
I don't see any error here. Please provide a proper description on the issues you're facing.

**Comment by akhilgorantala** [comment]
@jonasbark even app has a update its not showing any dialog or fullscreen update alert.

**Comment by jonasbark** [comment]
what does "even app has a update" mean exactly?

**Comment by akhilgorantala** [comment]
even i have a update for app its not showing the alert dialog in app.

**Comment by jonasbark** [comment]
what makes you think you have an update? does the update show in Play Store itself?
I'm currently using this plugin as well and it works just fine.

**Comment by akhilgorantala** [comment]
ok then please share your code that your are using so we can figure it out.

**Comment by jonasbark** [comment]
https://github.com/jonasbark/flutter_in_app_update/blob/master/example/lib/main.dart - it's all there is.

**Comment by akhilgorantala** [comment]
@jonasbark this is not working i tried please check my code.

` AppUpdateInfo _updateInfo;

Future checkForUpdate() async {
InAppUpdate.checkForUpdate().then((info) {
setState(() {
_updateInfo = info;
});
}).catchError((e) {
//do nothing
});
}

void updateApp() {
_updateInfo?.updateAvailability == UpdateAvailability.updateAvailable
? () {
InAppUpdate.performImmediateUpdate();
}
: null;
} 

@OverRide
void initState() {
checkForUpdate();
updateApp();
}`

**Comment by jonasbark** [comment]
I can't help you if all you say is "is not working".
I need way more information, e.g. you left my "what makes you think you have an update?" question unanswered.

Oh and your code will not work because _updateInfo is always null when you call updateApp because that's the nature of the futures.  Stick to the documentation and example.

**Comment by akhilgorantala** [comment]
actually we need to check the update and if update is available, it need to show the dialog right. but user cant check the update by clicking the button. so i tried to call it in initState

**Comment by jonasbark** [comment]
You're calling updateApp() too early. You'll need to wait until checkForUpdate is done. 
Closing this ticket as it's clearly a developer issue.
