### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by carsondu22** [jonasbark/flutter_in_app_update#80]
Had this error when building:

e: /Users/carsondu/.pub-cache/hosted/pub.dartlang.org/in_app_update-2.0.0/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (226, 26): Type mismatch: inferred type is String? but String was expected

* What went wrong:
Execution failed for task ':in_app_update:compileDebugKotlin'.

Flutter version: 3.0.2
ext.kotlin_version = '1.5.10'

**Comment by jonasbark** [comment]
You should use plugin version 3.0.0
