### ISSUE TITLE
Install Error(-10): The app is not owned by any user on this device.

### ISSUE THREAD

**Issue by mhrzd** [jonasbark/flutter_in_app_update#87]
The `checkForUpdate()` method throws an exception:
`PlatformException(TASK_FAILURE, Install Error(-10): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_APP_NOT_OWNED), null, null)`
I'm not sure why is this happening.

**Comment by jonasbark** [comment]
https://github.com/jonasbark/flutter_in_app_update#getting-error_api_not_available-error

**Comment by mhrzd** [comment]
I installed the app using Google Play and the error's gone, Thank you.
