### ISSUE TITLE
Task :in_app_update:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by AliPunjabi** [jonasbark/flutter_in_app_update#93]
Why I am getting this exception:
`/Users/mac/.pub-cache/hosted/pub.dev/in_app_update-2.0.0/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (226, 26): Type mismatch:
inferred type is String? but String was expected`

**Comment by aobsedtawut** [comment]
I ran into this problem too.

**Comment by jonasbark** [comment]
4.1.0 is the latest version - you're using 2.0.0. Do an upgrade.
