### ISSUE TITLE
Install Error(-10)

### ISSUE THREAD

**Issue by FoloosiApps** [jonasbark/flutter_in_app_update#96]
**-10: Install Error(-10): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_APP_NOT_OWNED)**

How can i fix this case?

**Comment by handika231** [comment]
@FoloosiApps your app from google play store ?

**Comment by FoloosiApps** [comment]
@handika231 My app is now google play store. But Inapp update is not working

**Comment by jonasbark** [comment]
there's nothing to fix here - it will only work when installed directly from the Play Store.
